(()=>{'use strict';
const BUILD='0.3.0',SAVE_KEY='gra.prototype.save.v3',OLD_SAVE='gra.prototype.save.v2';
const OFFLINE_EFF=.05,OFFLINE_CAP=12*3600,COMBO_STEP=50,MAX_COMBO_STEPS=10,COMBO_GRACE=6000,COMBO_DECAY=3000;
const $=id=>document.getElementById(id);const el={stage:$('stageNo'),currency:$('currency'),dps:$('dps'),worldStage:$('worldStage'),enemyPanel:$('enemyPanel'),enemyType:$('enemyType'),bossTimer:$('bossTimer'),hpFill:$('hpFill'),enemyHp:$('enemyHp'),enemyButton:$('enemyButton'),tapDamage:$('tapDamage'),comboMult:$('comboMult'),comboHits:$('comboHits'),floatLayer:$('floatLayer'),kills:$('kills'),bossKills:$('bossKills'),interactions:$('interactions'),autoState:$('autoState'),missionTitle:$('missionTitle'),missionDesc:$('missionDesc'),missionIndex:$('missionIndex'),missionFill:$('missionFill'),claimMission:$('claimMission'),tapUpgrade:$('tapUpgrade'),tapLevel:$('tapLevel'),tapCost:$('tapCost'),dpsUpgrade:$('dpsUpgrade'),dpsLevel:$('dpsLevel'),dpsCost:$('dpsCost'),worldInteract:$('worldInteract'),offlineModal:$('offlineModal'),offlineAmount:$('offlineAmount'),offlineTime:$('offlineTime'),claimOffline:$('claimOffline'),resetBtn:$('resetBtn'),toast:$('toast'),worldCanvas:$('worldCanvas')};
const defaultState=()=>({version:3,build:BUILD,currency:0,stage:1,kills:0,bossKills:0,tapLevel:1,dpsLevel:0,comboHits:0,lastTapAt:0,lastComboDecayAt:0,mission:0,missionClaims:0,interactions:0,lastSavedAt:Date.now(),createdAt:Date.now(),offlinePending:0,offlineSeconds:0,bossDeadline:0,enemyHp:null});
function load(){try{const r=localStorage.getItem(SAVE_KEY);if(r)return {...defaultState(),...JSON.parse(r)};const old=localStorage.getItem(OLD_SAVE);if(old){const p=JSON.parse(old),s=defaultState();s.currency=Number(p.currency)||0;s.interactions=Number(p.interactions)||0;return s}}catch(e){}return defaultState()}let state=load(),lastTick=performance.now();
function worldStage(){return state.stage>=20?3:state.stage>=10?2:1}const world=createLivingWorld(el.worldCanvas,{onWorldTap:()=>worldInteract(),onEntity:({kind})=>entityInteract(kind),onPopulation:()=>{},onEntityBusy:()=>toast('Za chwilę znów zareaguje')});world.setStage(worldStage());
function fmt(n){if(n<1e3)return Math.floor(n).toLocaleString('pl-PL');if(n<1e6)return (n/1e3).toFixed(n<1e4?1:0)+'k';if(n<1e9)return(n/1e6).toFixed(1)+'M';return(n/1e9).toFixed(1)+'B'}
function isBoss(){return state.stage%10===0}function baseEnemyHp(){return 20*Math.pow(1.30,state.stage-1)*(isBoss()?3:1)}function enemyMax(){return baseEnemyHp()}function reward(){return 8*Math.pow(1.27,state.stage-1)*(isBoss()?7:1)}function tapBase(){return 1*Math.pow(1.55,state.tapLevel-1)}function comboMult(){return 1+Math.min(MAX_COMBO_STEPS,Math.floor(state.comboHits/COMBO_STEP))*.1}function tapDamage(){return tapBase()*comboMult()}function dps(){return state.dpsLevel?2.2*Math.pow(1.62,state.dpsLevel-1):0}function tapUpgradeCost(){return Math.floor(20*Math.pow(1.58,state.tapLevel-1))}function dpsCost(){return Math.floor(500*Math.pow(1.65,state.dpsLevel))}
function ensureEnemy(){const max=enemyMax();if(state.enemyHp==null||state.enemyHp<=0||state.enemyHp>max*1.02)state.enemyHp=max;if(isBoss()&&!state.bossDeadline)state.bossDeadline=Date.now()+45000;if(!isBoss())state.bossDeadline=0}
const missions=[
 {t:'Pierwsza krew',d:'Pokonaj 5 stworzeń',v:()=>state.kills,m:5,r:80},
 {t:'Silniejszy impuls',d:'Ulepsz atak do poziomu 4',v:()=>state.tapLevel,m:4,r:180},
 {t:'Próba wodospadu',d:'Dotrzyj do Stage 10',v:()=>state.stage,m:10,r:320},
 {t:'Strażnik progu',d:'Pokonaj pierwszego bossa',v:()=>state.bossKills,m:1,r:450},
 {t:'Żywy sojusznik',d:'Odblokuj Strażnika (DPS)',v:()=>state.dpsLevel,m:1,r:700},
 {t:'Rozkwit doliny',d:'Dotrzyj do Stage 20',v:()=>state.stage,m:20,r:1200},
 {t:'Mieszkańcy doliny',d:'Wejdź w interakcję 3 razy',v:()=>state.interactions,m:3,r:1600},
 {t:'Serce Verdant Falls',d:'Pokonaj 3 bossów',v:()=>state.bossKills,m:3,r:3000},
];
function save(){state.lastSavedAt=Date.now();state.build=BUILD;localStorage.setItem(SAVE_KEY,JSON.stringify(state))}function toast(t){el.toast.textContent=t;el.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.add('hidden'),1300)}function floatNum(t,color='#fff4a6'){const d=document.createElement('div');d.className='float-num';d.textContent=t;d.style.color=color;d.style.setProperty('--drift',`${Math.round((Math.random()-.5)*50)}px`);el.floatLayer.appendChild(d);setTimeout(()=>d.remove(),680)}
function attack(){ensureEnemy();const now=Date.now();state.comboHits=Math.min(500,state.comboHits+1);state.lastTapAt=now;state.lastComboDecayAt=now;const dmg=tapDamage();state.enemyHp-=dmg;floatNum('-'+fmt(dmg));world.pulse();if(state.enemyHp<=0)killEnemy();render()}
function killEnemy(){const boss=isBoss();const gain=reward();state.currency+=gain;state.kills++;if(boss)state.bossKills++;floatNum('+'+fmt(gain),'#ffd66e');toast(boss?'BOSS POKONANY!':'Stworzenie pokonane');state.stage++;state.enemyHp=null;state.bossDeadline=0;const ws=worldStage();if(ws!==world.getStage()){world.setStage(ws);toast(ws===2?'Dolina rozkwita — nowy poziom świata!':'Osada ożywa — Stage 3!')}ensureEnemy();save()}
function buyTap(){const c=tapUpgradeCost();if(state.currency<c)return;state.currency-=c;state.tapLevel++;toast('Impuls wzmocniony');save();render()}
function buyDps(){if(state.stage<10)return;const c=dpsCost();if(state.currency<c)return;state.currency-=c;state.dpsLevel++;toast(state.dpsLevel===1?'Strażnik dołącza do walki':'Strażnik ulepszony');save();render()}
function worldInteract(){state.interactions++;state.currency+=5*worldStage();world.pulse();toast('Świat reaguje +'+(5*worldStage()));save();render()}function entityInteract(kind){state.interactions++;const r=kind==='npc'?12:8;state.currency+=r*worldStage();toast((kind==='npc'?'Mieszkaniec odpowiada':'Stworzenie reaguje')+' +'+r*worldStage());save();render()}
function missionReady(){const m=missions[state.mission];return m&&m.v()>=m.m}function claimMission(){const m=missions[state.mission];if(!m||!missionReady())return;state.currency+=m.r;state.missionClaims++;toast('Misja ukończona +'+fmt(m.r));state.mission=Math.min(missions.length,state.mission+1);save();render()}
function updateCombo(now){if(!state.lastTapAt||state.comboHits<50)return;if(now-state.lastTapAt<COMBO_GRACE)return;if(!state.lastComboDecayAt||state.lastComboDecayAt<=state.lastTapAt)state.lastComboDecayAt=state.lastTapAt+COMBO_GRACE;const e=now-state.lastComboDecayAt;if(e>=COMBO_DECAY){const n=Math.floor(e/COMBO_DECAY);state.comboHits=Math.max(0,state.comboHits-n*50);state.lastComboDecayAt+=n*COMBO_DECAY}}
function updateBoss(now){if(isBoss()&&state.bossDeadline&&now>=state.bossDeadline){toast('Boss odparł atak — spróbuj ponownie');state.enemyHp=enemyMax();state.bossDeadline=Date.now()+45000;state.comboHits=0}}
function render(){ensureEnemy();const max=enemyMax(),hp=Math.max(0,state.enemyHp);el.stage.textContent=state.stage;el.currency.textContent=fmt(state.currency);el.dps.textContent=fmt(dps());el.worldStage.textContent=worldStage();el.enemyPanel.classList.toggle('boss',isBoss());el.enemyType.textContent=isBoss()?'STRAŻNIK WODOSPADU • BOSS':'DZIKIE STWORZENIE';el.hpFill.style.width=Math.max(0,hp/max*100)+'%';el.enemyHp.textContent=`${fmt(hp)} / ${fmt(max)}`;el.tapDamage.textContent=fmt(tapDamage());el.comboMult.textContent='x'+comboMult().toFixed(1);el.comboHits.textContent=state.comboHits>=500?'MAX':(state.comboHits%50)+'/50';el.kills.textContent=state.kills;el.bossKills.textContent=state.bossKills;el.interactions.textContent=state.interactions;el.autoState.textContent=state.dpsLevel?'ON':'OFF';el.tapLevel.textContent='Lv. '+state.tapLevel;el.tapCost.textContent=fmt(tapUpgradeCost());el.tapUpgrade.disabled=state.currency<tapUpgradeCost();el.dpsLevel.textContent=state.dpsLevel?'Lv. '+state.dpsLevel:'Zablokowany';el.dpsCost.textContent=state.stage<10?'Stage 10':fmt(dpsCost());el.dpsUpgrade.disabled=state.stage<10||state.currency<dpsCost();const m=missions[state.mission];if(m){el.missionIndex.textContent=(state.mission+1)+'/8';el.missionTitle.textContent=m.t;el.missionDesc.textContent=m.d+` • nagroda ${fmt(m.r)}`;el.missionFill.style.width=Math.min(100,m.v()/m.m*100)+'%';el.claimMission.disabled=!missionReady()}else{el.missionIndex.textContent='8/8';el.missionTitle.textContent='Wszystkie misje ukończone';el.missionDesc.textContent='Vertical Slice zakończony';el.missionFill.style.width='100%';el.claimMission.disabled=true;el.claimMission.textContent='UKOŃCZONE'}if(isBoss()&&state.bossDeadline){const s=Math.max(0,Math.ceil((state.bossDeadline-Date.now())/1000));el.bossTimer.textContent=s+'s'}else el.bossTimer.textContent=''}
function calcOffline(){const elapsed=Math.max(0,Math.min(OFFLINE_CAP,(Date.now()-(state.lastSavedAt||Date.now()))/1000));if(elapsed<30||dps()<=0)return;const a=dps()*elapsed*OFFLINE_EFF;if(a<1)return;state.offlinePending=a;state.offlineSeconds=elapsed;el.offlineAmount.textContent='+'+fmt(a);el.offlineTime.textContent=Math.floor(elapsed/60)+' min poza grą';el.offlineModal.classList.remove('hidden')}
function claimOffline(){state.currency+=state.offlinePending||0;state.offlinePending=0;state.offlineSeconds=0;el.offlineModal.classList.add('hidden');save();render()}
function tick(p){const dt=Math.min(.25,(p-lastTick)/1000);lastTick=p;updateCombo(Date.now());updateBoss(Date.now());if(dps()>0){state.enemyHp-=dps()*dt;if(state.enemyHp<=0)killEnemy()}render();requestAnimationFrame(tick)}
el.enemyButton.addEventListener('pointerdown',e=>{e.preventDefault();attack()});el.tapUpgrade.addEventListener('click',buyTap);el.dpsUpgrade.addEventListener('click',buyDps);el.claimMission.addEventListener('click',claimMission);el.worldInteract.addEventListener('click',worldInteract);el.claimOffline.addEventListener('click',claimOffline);el.resetBtn.addEventListener('click',()=>{if(confirm('Zresetować build v0.3.0?')){localStorage.removeItem(SAVE_KEY);state=defaultState();world.setStage(1);save();render()}});document.addEventListener('visibilitychange',()=>{if(document.hidden)save();else calcOffline()});window.addEventListener('pagehide',save);setInterval(save,5000);ensureEnemy();calcOffline();render();requestAnimationFrame(tick);window.GRA_DEBUG={state:()=>JSON.parse(JSON.stringify(state)),addCurrency:n=>{state.currency+=Number(n)||0;render()},setStage:n=>{state.stage=Math.max(1,Number(n)||1);state.enemyHp=null;world.setStage(worldStage());ensureEnemy();render()},save};
})();